apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeweb
  labels:
    app: nodeweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeweb
  template:
    metadata:
      labels:
        app: nodeweb
    spec:
      containers:
      - name: nodeweb
        image: hackbuhl/nodeapi
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            # cpu: "10m"
          limits:
            memory: "16Mi"
            # cpu: "10m"